import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import Navbar from "./_Component/Navbar/Navbar";
import Footer from "./_Component/Footer/Footer";
import { Toaster } from "@/components/ui/sonner"
import MySessionProvider from "./MySessionProvider/MySessionProvider";
import  CartContextProvider  from '../context/cartContext';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>  
          <CartContextProvider>
        <Navbar />
        {children}
        <Toaster />
        <Footer />
          </CartContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
